### ISSUE TITLE
js should not run in the main world

### ISSUE THREAD

**Issue by bridiver** [brave/electron#109]
All js should run in an isolated world to protect internal functions from scripts running in the page content. Any js that is exposed to the main world should use safe builtins

**Comment by bridiver** [comment]
Test plan:
Anything that uses ipc from a content script is potentially affected by this change. Things that should be tested include ad replacement, language settings and spell check. In particular we want to look at things happening in an iframe vs the main frame
1. Go to https://zyan.scripts.mit.edu/brave/textarea.html and ensure spellcheck works in both the main frame and the iframe
2. Same as above but change the language setting first
3. Go to https://zyan.scripts.mit.edu/brave/slashdot.html and turn on brave ads. Brave ads should appear in the iframed slashdot page

**Comment by bbondy** [comment]
cc @alexwykoff
