### ISSUE TITLE
Context menu fails to open when manifest icon is missing

### ISSUE THREAD

**Issue by jonathansampson** [brave/electron#113]
Brave: 0.12.13
Muon: 1.4.30
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev
os.platform: win32
os.release: 10.0.14393
os.arch: x64

**Reproduction Steps:**
1. Enable the LastPass extension
2. Right-click in Brave to confirm presence of LastPass icon, and menu item (leave Brave open)
3. Navigate to `%appdata%\Roaming\brave\Extensions\hdokiejnpimakedhajhdlcegeplioahd`
4. Enter the extension folder, and rename `icon2.png` to `icon2.png_`.
5. Right-click in Brave
6. Note that context menu does not open

**Alternative Steps:**
1. Enable the LastPass extension
2. Navigate to `%appdata%\Roaming\brave\Extensions\hdokiejnpimakedhajhdlcegeplioahd`
3. Remove `"16": "icon2.png",` from `manifest.json` and save
4. Restart Brave
5. Note that right-click no longer opens a context menu

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6112 :smile:
