### ISSUE TITLE
Debug builds fail to link on Windows

### ISSUE THREAD

**Issue by Mossop** [brave/electron#67]
* Brave version: 1.4.8
* Operating system: Windows 10

Debug builds fail at the linking stage with this error:

    brave_lib.lib(brave_lib.profile_writer.obj) : error LNK2019: unresolved external symbol "public: __cdecl TemplateURL::~TemplateURL(void)" (??1TemplateURL@@QEAA@XZ) referenced in function "public: void * __cdecl TemplateURL::`scalar deleting destructor'(unsigned int)" (??_GTemplateURL@@QEAAPEAXI@Z)
    brave.exe : fatal error LNK1120: 1 unresolved externals

Looks related to the importer code that was added in #57

**Comment by bridiver** [comment]
thanks! I had been testing on windows 7 and the debug builds didn't work at all so I didn't bother to fix the linking issues, but I until recently I didn't realize they worked correctly on win10 so we'll get this fixed

**Comment by bridiver** [comment]
cc @darkdh
