### ISSUE TITLE
[Question] Is this fork usable as a drop-in replacement for upstream Electron?

### ISSUE THREAD

**Issue by lostfictions** [brave/electron#87]
[Nativefier](https://github.com/jiahaog/nativefier) is a utility in the vein of [Fluid](http://fluidapp.com/) or Mozilla's defunct [Prism](https://en.wikipedia.org/wiki/Mozilla_Prism) that uses Electron to create site-specific browsers. They're isolated from each other in terms of cookies, storage, etc. and lack the usual browser chrome.

I tried to briefly touch on some of the security challenges of using Electron in a browser-like capacity in jiahaog/nativefier#288 -- challenges I'm sure the Brave team is familiar with. Would your fork of `electron-prebuilt` potentially be usable as a drop-in for Nativefier's use case?

**Comment by posix4e** [comment]
I am not sure. Our fork is more targeted as a webbrowser than an app platform. No reason why it shouldn't work. Certainly we have some security advantages.

**Comment by bridiver** [comment]
our fork is mostly compatible at the moment, but will have some significant changes with the chromium54 update. In particular we will no longer support running node in any renderer process. Node will only run in the browser process. Things like ipc are supported in the renderer process through custom chrome.* apis. Our goal is to have a project that can be re-used by people looking for more "browser-like" features than electron provides, but right now our resources are focused 100% on Brave
